services:
  - type: web
    plan: free
    name: trab1-web
    runtime: python
    repo: https://github.com/luizfneves404/trab1-web.git
    buildCommand: "uv sync"
    startCommand: "uv run gunicorn trab1_web.asgi:application -k
      uvicorn.workers.UvicornWorker"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
