services:
  - type: web
    plan: free
    name: Taskmaster
    runtime: python
    repo: https://github.com/luizfneves404/trab1-web.git
    buildCommand: "uv sync && uv run manage.py collectstatic --noinput"
    startCommand: "uv run gunicorn trab1_web.asgi:application -k
      uvicorn.workers.UvicornWorker"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "[\"trab1-web.onrender.com\"]"
      - key: DATABASE_URL
        sync: false
